# Generated by Django 4.1.3 on 2022-11-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
            ],
        ),
    ]
