# Generated by Django 4.1.3 on 2022-11-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='professor_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
    ]
