# Generated by Django 4.1.3 on 2022-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_professor_department_review_professor_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
