# Generated by Django 4.1.3 on 2022-11-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_professor_rating_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
