# Generated by Django 4.1.3 on 2022-11-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_review_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_check',
            field=models.BooleanField(null=True),
        ),
    ]
