# Generated by Django 4.1.3 on 2022-11-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_review_review_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
