# Generated by Django 4.1.3 on 2022-11-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_review_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
