# Generated by Django 4.1.3 on 2022-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_professor_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='picture',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
