# Generated by Django 4.1.3 on 2022-11-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='courses',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
