# Generated by Django 4.1.3 on 2022-11-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
